<a href="https://colab.research.google.com/github/HarisAnsari75/Black_Friday_Analysis/blob/main/Black_friday_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **Black friday analysis**

In [ ]:
import pandas as pd
df=pd.read_csv('/content/blackfriday.csv')
df.head(10) #show data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,NaN,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,NaN,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,NaN,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,NaN,NaN,7871

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.tail(5) #show last 5 row value

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
550063,1006033,P00372445,M,51-55,13,B,1,1,20,NaN,NaN,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,NaN,NaN,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,NaN,NaN,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,NaN,NaN,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,NaN,NaN,490

In [ ]:
df.duplicated() #checking duplicate value
sum(df.duplicated()) #checking sum duplicate value

0

In [ ]:
[i for i in df.columns if 'Product' in i] # checking colms is present in df or not

['Product_ID',
 'Product_Category_1',
 'Product_Category_2',
 'Product_Category_3']

In [ ]:
# create new df of product index
df_product=  df[['Product_ID','Product_Category_1','Product_Category_2','Product_Category_3']]
df_product

       Product_ID  Product_Category_1  Product_Category_2  Product_Category_3
0       P00069042                   3                 NaN                 NaN
1       P00248942                   1                 6.0                14.0
2       P00087842                  12                 NaN                 NaN
3       P00085442                  12                14.0                 NaN
4       P00285442                   8                 NaN                 NaN
...           ...                 ...                 ...                 ...
550063  P00372445                  20                 NaN                 NaN
550064  P00375436                  20                 NaN                 NaN
550065  P00375436                  20                 NaN                 NaN
550066  P00375436                  20                 NaN                 NaN
550067  P00371644                  20                 NaN                 NaN

[550068 rows x 4 columns]

In [ ]:
df.axes #list of rows and columns

[RangeIndex(start=0, stop=550068, step=1),
 Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
        'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
        'Product_Category_2', 'Product_Category_3', 'Purchase'],
       dtype='object')]

In [ ]:
df.Gender.values

array(['F', 'F', 'F', ..., 'F', 'F', 'F'], dtype=object)

In [ ]:
df.size

6600816

In [ ]:
df.info() # data information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB

In [ ]:
df["Purchase"]=df["Purchase"].astype ("float64") #changing datatype of colms
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  float64
dtypes: float64(3), int64(4), object(5)
memory usage: 50.4+ MB

In [ ]:
# Fill missing values in 'Purchase' with the mean before changing the datatype
df["Purchase"] = df["Purchase"].fillna(df["Purchase"].mean())
df["Purchase"]=df["Purchase"].astype ("int64") #changing back to old datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB

In [ ]:
df.describe()   #this gives statistied of all numerical value colms

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,5.500680e+05,550068.000000,550068.000000,550068.000000,376430.000000,166821.000000,550068.000000
mean,1.003029e+06,8.076707,0.409653,5.404270,9.842329,12.668243,9263.968713
std,1.727592e+03,6.522660,0.491770,3.936211,5.086590,4.125338,5023.065394
min,1.000001e+06,0.000000,0.000000,1.000000,2.000000,3.000000,12.000000
25%,1.001516e+06,2.000000,0.000000,1.000000,5.000000,9.000000,5823.000000
50%,1.003077e+06,7.000000,0.000000,5.000000,9.000000,14.000000,8047.000000
75%,1.004478e+06,14.000000,1.000000,8.000000,15.000000,16.000000,12054.000000
max,1.006040e+06,20.000000,1.000000,20.000000,18.000000,18.000000,23961.000000

In [ ]:
df.describe(include=["object"]) #Used to give statitics of object datatype colm

       Product_ID  Gender     Age City_Category Stay_In_Current_City_Years
count      550068  550068  550068        550068                     550068
unique       3631       2       7             3                          5
top     P00265242       M   26-35             B                          1
freq         1880  414259  219587        231173                     193821

In [ ]:
df["Product_ID"].value_counts() # show which product is purchase how many time

Product_ID
P00265242    1880
P00025442    1615
P00110742    1612
P00112142    1562
P00057642    1470
             ...
P00325342       1
P00312542       1
P00008942       1
P00315142       1
P00365942       1
Name: count, Length: 3631, dtype: int64

In [ ]:
df["Product_ID"].value_counts (normalize=True) #pertentage of product purchased

Product_ID
P00265242    0.003418
P00025442    0.002936
P00110742    0.002931
P00112142    0.002840
P00057642    0.002672
               ...
P00325342    0.000002
P00312542    0.000002
P00008942    0.000002
P00315142    0.000002
P00365942    0.000002
Name: proportion, Length: 3631, dtype: float64

In [ ]:
round(df["Product_ID"].value_counts(normalize=True)*100,3) # percentage of product purchased
                                                           # multiply by 100 to get percentage
                                                           # round it up with 3 digit

Product_ID
P00265242    0.342
P00025442    0.294
P00110742    0.293
P00112142    0.284
P00057642    0.267
             ...
P00325342    0.000
P00312542    0.000
P00008942    0.000
P00315142    0.000
P00365942    0.000
Name: proportion, Length: 3631, dtype: float64

In [ ]:
round(df["Product_ID"].value_counts(normalize=True)*100,3) .sum() #sum of all product purchased should be 100%

np.float64(99.97600000000001)

In [ ]:
df.isnull().sum() #handling missing values   #sum shows no.of null values

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [ ]:
df.Product_Category_3          #checking null values

0          NaN
1         14.0
2          NaN
3          NaN
4          NaN
          ...
550063     NaN
550064     NaN
550065     NaN
550066     NaN
550067     NaN
Name: Product_Category_3, Length: 550068, dtype: float64

In [ ]:
df_temp=df.drop('Product_Category_3',axis=1,inplace=False) #droping colm

In [ ]:
df_temp.info()  # there is no Product_category_3 colm
df.isnull()     #checking all colms null value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     550068 non-null  int64
 1   Product_ID                  550068 non-null  object
 2   Gender                      550068 non-null  object
 3   Age                         550068 non-null  object
 4   Occupation                  550068 non-null  int64
 5   City_Category               550068 non-null  object
 6   Stay_In_Current_City_Years  550068 non-null  object
 7   Marital_Status              550068 non-null  int64
 8   Product_Category_1          550068 non-null  int64
 9   Product_Category_2          376430 non-null  float64
 10  Purchase                    550068 non-null  int64
dtypes: float64(1), int64(5), object(5)
memory usage: 46.2+ MB

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,False,False,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,False,False,False,False,False,False,False,False,False,True,True,False
550064,False,False,False,False,False,False,False,False,False,True,True,False
550065,False,False,False,False,False,False,False,False,False,True,True,False
550066,False,False,False,False,False,False,False,False,False,True,True,False
550067,False,False,False,False,False,False,False,False,False,True,True,False

In [ ]:
df=df.fillna(method='ffill')    # ffill function is forward filling function
df=df.fillna(method='bfill')    # bfill function is backward filling function

/tmp/ipython-input-3942605945.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='ffill')    # ffill function is forward filling function
/tmp/ipython-input-3942605945.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method='bfill')    # bfill function is backward filling function

In [ ]:
  df.isnull().sum()  #with ffill there was 1,1 null value
                     # and with bfill it become 0 null present

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [ ]:
df1=df.copy()    #creating copy of df for loc,iloc function

In [ ]:
df.loc[0,'Product_ID']    #taking 0 row and colm product_id

'P00069042'

In [ ]:
df.loc[:,'Product_ID']   # : is for taking all rows (5:10 this will take 5 to 10th row)

0         P00069042
1         P00248942
2         P00087842
3         P00085442
4         P00285442
            ...
550063    P00372445
550064    P00375436
550065    P00375436
550066    P00375436
550067    P00371644
Name: Product_ID, Length: 550068, dtype: object

In [ ]:
df.loc[0:4,['Age','Product_ID']]    #with multipl colm

    Age Product_ID
0  0-17  P00069042
1  0-17  P00248942
2  0-17  P00087842
3  0-17  P00085442
4   55+  P00285442

In [ ]:
df.loc [55:100]   # taking from 55 to 100

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
55,1000014,P00276642,M,36-45,0,C,0,0,8,11.0,6.0,5848
56,1000015,P00334242,M,26-35,7,A,1,0,1,8.0,6.0,19653
57,1000015,P00247542,M,26-35,7,A,1,0,8,16.0,6.0,5958
58,1000015,P00338442,M,26-35,7,A,1,0,1,16.0,6.0,11415
59,1000015,P00275142,M,26-35,7,A,1,0,5,8.0,6.0,5380
60,1000015,P00333042,M,26-35,7,A,1,0,5,8.0,6.0,3594
61,1000015,P00166242,M,26-35,7,A,1,0,8,8.0,6.0,4209
62,1000015,P00161942,M,26-35,7,A,1,0,5,8.0,6.0,5407
63,1000015,P00348242,M,26-35,7,A,1,0,8,8.0,6.0,7803
64,1000015,P00042142,M,26-35,7,A,1,0,1,2.0,6.0,11458
65,1000016,P00244242,F,36-45,0,C,0,1,1,2.0,15.0,11755
66,1000016,P00217742,F,36-45,0,C,0,1,5,14.0,15.0,8702
67,1000017,P00019342,M,51-55,1,C,0,0,1,6.0,15.0,15872
68,1000017,P00100642,M,51-55,1,C,0,0,5,15.0,15.0,8609
69,1000017,P00073842,M,51-55,1,C,0,0,1,15.0,17.0,15172
70,1000018,P00366542,F,18-25,3,B,3,0,5,15.0,17.0,1780
71,1000018,P00190742,F,18-25,3,B,3,0,3,4.0,9.0,10754
72,1000018,P00151842,F,18-25,3,B,3,0,4,8.0,9.0,2802
73,1000018,P00112642,F,18-25,3,B,3,0,1,2.0,5.0,19473
74,1000018,P00118442,F,18-25,3,B,3,0,1,2.0,5.0,19672
75,1000018,P00034442,F,18-25,3,B,3,0,1,14.0,16.0,19313
76,1000018,P00222242,F,18-25,3,B,3,0,1,2.0,13.0,15182
77,1000018,P00118342,F,18-25,3,B,3,0,2,3.0,15.0,15985
78,1000018,P00324742,F,18-25,3,B,3,0,2,9.0,14.0,16454
79,1000018,P00190042,F,18-25,3,B,3,0,3,4.0,5.0,13551
80,1000018,P0094142,F,18-25,3,B,3,0,4,5.0,5.0,697
81,1000018,P00138542,F,18-25,3,B,3,0,5,6.0,5.0,7030
82,1000018,P00158542,F,18-25,3,B,3,0,5,6.0,13.0,5430
83,1000018,P00157542,F,18-25,3,B,3,0,8,14.0,13.0,8011
84,1000018,P00044142,F,18-25,3,B,3,0,8,16.0,13.0,5912
85,1000019,P00112542,M,0-17,10,A,3,0,1,11.0,15.0,7746
86,1000019,P00339542,M,0-17,10,A,3,0,1,11.0,15.0,19525
87,1000019,P00127842,M,0-17,10,A,3,0,1,2.0,15.0,11959
88,1000019,P00125942,M,0-17,10,A,3,0,1,2.0,15.0,19172
89,1000019,P00251342,M,0-17,10,A,3,0,5,11.0,15.0,8773
90,1000019,P00249642,M,0-17,10,A,3,0,3,5.0,15.0,11023
91,1000019,P00124842,M,0-17,10,A,3,0,11,5.0,15.0,4654
92,1000019,P00250642,M,0-17,10,A,3,0,11,5.0,15.0,4664
93,1000019,P00058142,M,0-17,10,A,3,0,3,4.0,12.0,8290
94,1000019,P00117442,M,0-17,10,A,3,0,5,14.0,12.0,7011
95,1000019,P00251642,M,0-17,10,A,3,0,1,2.0,4.0,4211
96,1000019,P00244842,M,0-17,10,A,3,0,11,2.0,4.0,1539
97,1000021,P00220242,M,18-25,16,B,0,0,3,12.0,4.0,3055
98,1000022,P00351142,M,18-25,15,A,4+,0,1,8.0,17.0,12099
99,1000022,P00213242,M,18-25,15,A,4+,0,5,8.0,17.0,8797
100,1000022,P00195942,M,18-25,15,A,4+,0,3,4.0,17.0,10681

In [ ]:
df1.iloc[:,0:5]    #taking 0 to 5th colms

        User_ID Product_ID Gender    Age  Occupation
0       1000001  P00069042      F   0-17          10
1       1000001  P00248942      F   0-17          10
2       1000001  P00087842      F   0-17          10
3       1000001  P00085442      F   0-17          10
4       1000002  P00285442      M    55+          16
...         ...        ...    ...    ...         ...
550063  1006033  P00372445      M  51-55          13
550064  1006035  P00375436      F  26-35           1
550065  1006036  P00375436      F  26-35          15
550066  1006038  P00375436      F    55+           1
550067  1006039  P00371644      F  46-50           0

[550068 rows x 5 columns]

In [ ]:
df1.iloc[-1]   #iloc  #last rows entry

User_ID                         1006039
Product_ID                    P00371644
Gender                                F
Age                               46-50
Occupation                            0
City_Category                         B
Stay_In_Current_City_Years           4+
Marital_Status                        1
Product_Category_1                   20
Product_Category_2                  2.0
Product_Category_3                 11.0
Purchase                            490
Name: 550067, dtype: object

In [ ]:
df1.iloc[[3,5,6,8,30,35],    [1,3,5,6]]   #row [3,6,8,30,35]      colm[1,3,5,6]

   Product_ID    Age City_Category Stay_In_Current_City_Years
3   P00085442   0-17             A                          2
5   P00193542  26-35             A                          3
6   P00184942  46-50             B                          2
8    P0097242  46-50             B                          2
30  P00118742  36-45             B                         4+
35  P00105942  36-45             B                         4+

In [ ]:
df1['Purchase'].idxmax()    #this gives the no.of max purchase row

87440

In [ ]:
df1.Purchase[df1['Purchase'].idxmax()] #this gives the exact amount of max purchase value

np.int64(23961)

In [ ]:
df1.at[2,'Purchase']   #with loc #3rd row in purchase colm

np.int64(1422)

In [ ]:
df1.iat[2,11]     #with iloc #3rd row and 11th colm

np.int64(1422)

In [ ]:
df.loc[((df['User_ID']== 1006039) & (df ['Product_ID'] == 'P00371644')) ,'Purchase']

550067    490
Name: Purchase, dtype: int64

In [ ]:
df.loc [550067,:]   #Getting info of row 550067

User_ID                         1006039
Product_ID                    P00371644
Gender                                F
Age                               46-50
Occupation                            0
City_Category                         B
Stay_In_Current_City_Years           4+
Marital_Status                        1
Product_Category_1                   20
Product_Category_2                  2.0
Product_Category_3                 11.0
Purchase                            490
Name: 550067, dtype: object

In [ ]:
df[~(df['Gender'] == 'F') & (df['City_Category'] == 'B') < 550067]   #Negation nootation

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,6.0,14.0,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,6.0,14.0,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,14.0,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,14.0,14.0,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,M,51-55,13,B,1,1,20,2.0,11.0,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,2.0,11.0,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,2.0,11.0,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,2.0,11.0,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,2.0,11.0,490

In [ ]:
values = [1006038, 'P00375436','F','55+',1,'C','2',0,20,2.0,11.0,365]

df1_indexed=df1.isin(values)
df1_indexed

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,False,False,True,False,False,False,True,True,False,False,False,False
1,False,False,True,False,False,False,True,True,True,False,False,False
2,False,False,True,False,False,False,True,True,False,False,False,False
3,False,False,True,False,False,False,True,True,False,False,False,False
4,False,False,False,True,False,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,False,False,False,False,False,False,False,True,True,True,True,False
550064,False,True,True,False,True,True,False,True,True,True,True,False
550065,False,True,True,False,False,False,False,True,True,True,True,False
550066,True,True,True,True,True,True,True,True,True,True,True,True
550067,False,False,True,False,True,False,False,True,True,True,True,False

In [ ]:
df1_indexed=df1.isin(values).all(axis=1) #making new row on axis 1
df1[df1_indexed]

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
550066,1006038,P00375436,F,55+,1,C,2,0,20,2.0,11.0,365

In [ ]:
newdf=df.mask(df['Occupation'] !=10)      #making occupation which is not equal to 10
newdf.head(10)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001.0,P00069042,F,0-17,10.0,A,2,0.0,3.0,6.0,14.0,8370.0
1,1000001.0,P00248942,F,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,1000001.0,P00087842,F,0-17,10.0,A,2,0.0,12.0,6.0,14.0,1422.0
3,1000001.0,P00085442,F,0-17,10.0,A,2,0.0,12.0,14.0,14.0,1057.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.sort_index (ascending=False)   #sort in descending order    #sort index

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,2.0,11.0,490
550066,1006038,P00375436,F,55+,1,C,2,0,20,2.0,11.0,365
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,2.0,11.0,137
550064,1006035,P00375436,F,26-35,1,C,3,0,20,2.0,11.0,371
550063,1006033,P00372445,M,51-55,13,B,1,1,20,2.0,11.0,368
...,...,...,...,...,...,...,...,...,...,...,...,...
4,1000002,P00285442,M,55+,16,C,4+,0,8,14.0,14.0,7969
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,14.0,1057
2,1000001,P00087842,F,0-17,10,A,2,0,12,6.0,14.0,1422
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
0,1000001,P00069042,F,0-17,10,A,2,0,3,6.0,14.0,8370

In [ ]:
df.sort_index(axis=1) #axis=1 will sort in colms name in ascending

,Age,City_Category,Gender,Marital_Status,Occupation,Product_Category_1,Product_Category_2,Product_Category_3,Product_ID,Purchase,Stay_In_Current_City_Years,User_ID
0,0-17,A,F,0,10,3,6.0,14.0,P00069042,8370,2,1000001
1,0-17,A,F,0,10,1,6.0,14.0,P00248942,15200,2,1000001
2,0-17,A,F,0,10,12,6.0,14.0,P00087842,1422,2,1000001
3,0-17,A,F,0,10,12,14.0,14.0,P00085442,1057,2,1000001
4,55+,C,M,0,16,8,14.0,14.0,P00285442,7969,4+,1000002
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,51-55,B,M,1,13,20,2.0,11.0,P00372445,368,1,1006033
550064,26-35,C,F,0,1,20,2.0,11.0,P00375436,371,3,1006035
550065,26-35,B,F,1,15,20,2.0,11.0,P00375436,137,4+,1006036
550066,55+,C,F,0,1,20,2.0,11.0,P00375436,365,2,1006038
550067,46-50,B,F,1,0,20,2.0,11.0,P00371644,490,4+,1006039

In [ ]:
df.sort_values(by=['Purchase','Age'],ascending=False)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
87440,1001474,P00052842,M,26-35,4,A,2,1,10,15.0,8.0,23961
93016,1002272,P00052842,M,26-35,0,C,1,0,10,15.0,8.0,23961
370891,1003160,P00052842,M,26-35,17,C,3,0,10,15.0,8.0,23961
321782,1001577,P00052842,M,55+,0,C,1,1,10,15.0,17.0,23960
349658,1005848,P00119342,M,51-55,20,A,0,1,10,13.0,5.0,23960
...,...,...,...,...,...,...,...,...,...,...,...,...
549165,1004733,P00370853,M,18-25,18,C,1,0,19,2.0,11.0,12
549477,1005184,P00370293,M,18-25,20,B,4+,1,19,2.0,11.0,12
546045,1000194,P00370853,F,0-17,10,C,3,0,19,2.0,11.0,12
546449,1000775,P00370853,M,0-17,17,C,1,0,19,2.0,11.0,12
550024,1005973,P00370293,M,0-17,10,C,4+,0,19,2.0,11.0,12

In [ ]:
top30 = df.sort_values(by=['Purchase'])

In [ ]:
top30

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
550024,1005973,P00370293,M,0-17,10,C,4+,0,19,2.0,11.0,12
549989,1005922,P00370853,M,55+,3,C,3,0,19,2.0,11.0,12
550029,1005979,P00370853,M,26-35,1,B,1,1,19,2.0,11.0,12
549632,1005416,P00370293,F,26-35,5,C,3,0,19,2.0,11.0,12
549661,1005454,P00370293,M,36-45,7,C,0,0,19,2.0,11.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...
292083,1003045,P00052842,M,46-50,1,B,2,1,10,15.0,17.0,23960
349658,1005848,P00119342,M,51-55,20,A,0,1,10,13.0,5.0,23960
370891,1003160,P00052842,M,26-35,17,C,3,0,10,15.0,8.0,23961
87440,1001474,P00052842,M,26-35,4,A,2,1,10,15.0,8.0,23961
93016,1002272,P00052842,M,26-35,0,C,1,0,10,15.0,8.0,23961

In [ ]:
df['Gender'].unique()

array(['F', 'M'], dtype=object)

In [ ]:
df['Gender'].value_counts(ascending=True) # take count of Gender colm

Gender
F    135809
M    414259
Name: count, dtype: int64

In [ ]:
df['Age'].value_counts(ascending=True) #take count of age colm

Age
0-17      15102
55+       21504
51-55     38501
46-50     45701
18-25     99660
36-45    110013
26-35    219587
Name: count, dtype: int64

In [ ]:
df['Gender']=df['Gender'].replace('F','Female')
df['Gender']=df['Gender'].replace('M','Male')
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,Female,0-17,10,A,2,0,3,6.0,14.0,8370
1,1000001,P00248942,Female,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,Female,0-17,10,A,2,0,12,6.0,14.0,1422
3,1000001,P00085442,Female,0-17,10,A,2,0,12,14.0,14.0,1057
4,1000002,P00285442,Male,55+,16,C,4+,0,8,14.0,14.0,7969

In [ ]:
df [['Age','User_ID']].values.tolist()    #its create the colm basis on need

[['0-17', 1000001],
 ['0-17', 1000001],
 ['0-17', 1000001],
 ['0-17', 1000001],
 ['55+', 1000002],
 ['26-35', 1000003],
 ['46-50', 1000004],
 ['46-50', 1000004],
 ['46-50', 1000004],
 ['26-35', 1000005],
 ['26-35', 1000005],
 ['26-35', 1000005],
 ['26-35', 1000005],
 ['26-35', 1000005],
 ['51-55', 1000006],
 ['51-55', 1000006],
 ['51-55', 1000006],
 ['51-55', 1000006],
 ['36-45', 1000007],
 ['26-35', 1000008],
 ['26-35', 1000008],
 ['26-35', 1000008],
 ['26-35', 1000008],
 ['26-35', 1000008],
 ['26-35', 1000008],
 ['26-35', 1000009],
 ['26-35', 1000009],
 ['26-35', 1000009],
 ['26-35', 1000009],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['36-45', 1000010],
 ['26-35', 1000011],
 ['26-35', 1000011],
 ['26-35', 1000011],
 ['26-35', 1000012],
 ['26-35', 1000012],
 ['46-50', 1000013],
 ['46-50', 1000013],
 ['46-50', 1000013],
 ['36-45', 1000014],
 ['26-35', 1000015],
 ['26-35', 1000015],
 ['26-35', 1000015],
 ['26-35', 1000015],
 ['26-35', 1000015],
 ['26-35', 1000015],
 ['26-35', 1000015],
 ['26-35', 1000015],
 ['26-35', 1000015],
 ['36-45', 1000016],
 ['36-45', 1000016],
 ['51-55', 1000017],
 ['51-55', 1000017],
 ['51-55', 1000017],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['18-25', 1000018],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['0-17', 1000019],
 ['18-25', 1000021],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['18-25', 1000022],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['36-45', 1000023],
 ['26-35', 1000024],
 ['26-35', 1000024],
 ['26-35', 1000024],
 ['18-25', 1000025],
 ['18-25', 1000025],
 ['18-25', 1000025],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000026],
 ['26-35', 1000027],
 ['26-35', 1000027],
 ['26-35', 1000027],
 ['26-35', 1000027],
 ['26-35', 1000027],
 ['26-35', 1000028],
 ['26-35', 1000028],
 ['26-35', 1000028],
 ['26-35', 1000028],
 ['26-35', 1000028],
 ['36-45', 1000029],
 ['36-45', 1000029],
 ['36-45', 1000029],
 ['36-45', 1000029],
 ['36-45', 1000030],
 ['36-45', 1000030],
 ['36-45', 1000030],
 ['55+', 1000031],
 ['55+', 1000031],
 ['55+', 1000031],
 ['55+', 1000031],
 ['26-35', 1000032],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['46-50', 1000033],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['18-25', 1000034],
 ['46-50', 1000035],
 ['46-50', 1000035],
 ['46-50', 1000035],
 ['46-50', 1000035],
 ['46-50', 1000035],
 ['46-50', 1000035],
 ['46-50', 1000035],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000036],
 ['26-35', 1000037],
 ['18-25', 1000039],
 ['18-25', 1000039],
 ['18-25', 1000041],
 ['18-25', 1000041],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000042],
 ['26-35', 1000043],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000044],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['46-50', 1000045],
 ['18-25', 1000046],
 ['18-25', 1000046],
 ['18-25', 1000046],
 ['18-25', 1000046],
 ['18-25', 1000047],
 ['18-25', 1000047],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['26-35', 1000048],
 ['18-25', 1000049],
 ['18-25', 1000049],
 ['18-25', 1000049],
 ['18-25', 1000049],
 ['18-25', 1000049],
 ['18-25', 1000049],
 ['26-35', 1000050],
 ['26-35', 1000050],
 ['0-17', 1000051],
 ['18-25', 1000052],
 ['18-25', 1000052],
 ['18-25', 1000052],
 ['18-25', 1000052],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['26-35', 1000053],
 ['51-55', 1000054],
 ['51-55', 1000054],
 ['36-45', 1000056],
 ['36-45', 1000056],
 ['36-45', 1000056],
 ['36-45', 1000056],
 ['18-25', 1000057],
 ['18-25', 1000057],
 ['18-25', 1000057],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['26-35', 1000058],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000059],
 ['51-55', 1000060],
 ['51-55', 1000060],
 ['26-35', 1000061],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['36-45', 1000062],
 ['18-25', 1000063],
 ['18-25', 1000063],
 ['18-25', 1000063],
 ['18-25', 1000063],
 ['18-25', 1000064],
 ['36-45', 1000065],
 ['36-45', 1000065],
 ['36-45', 1000065],
 ['36-45', 1000065],
 ['36-45', 1000065],
 ['36-45', 1000065],
 ['26-35', 1000066],
 ['51-55', 1000067],
 ['51-55', 1000067],
 ['51-55', 1000067],
 ['18-25', 1000068],
 ['18-25', 1000068],
 ['18-25', 1000068],
 ['26-35', 1000069],
 ['26-35', 1000069],
 ['18-25', 1000070],
 ['18-25', 1000070],
 ['26-35', 1000071],
 ['26-35', 1000071],
 ['26-35', 1000071],
 ['26-35', 1000071],
 ['46-50', 1000072],
 ['46-50', 1000072],
 ['18-25', 1000073],
 ['18-25', 1000073],
 ['18-25', 1000073],
 ['18-25', 1000073],
 ['18-25', 1000073],
 ['36-45', 1000074],
 ['36-45', 1000074],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['0-17', 1000075],
 ['36-45', 1000076],
 ['36-45', 1000076],
 ['36-45', 1000076],
 ['36-45', 1000076],
 ['36-45', 1000076],
 ['18-25', 1000077],
 ['18-25', 1000077],
 ['18-25', 1000077],
 ['46-50', 1000078],
 ['46-50', 1000078],
 ['46-50', 1000078],
 ['46-50', 1000078],
 ['46-50', 1000078],
 ['46-50', 1000078],
 ['46-50', 1000078],
 ['46-50', 1000078],
 ['46-50', 1000079],
 ['46-50', 1000079],
 ['55+', 1000080],
 ['55+', 1000080],
 ['55+', 1000080],
 ['26-35', 1000081],
 ['26-35', 1000082],
 ['26-35', 1000082],
 ['26-35', 1000083],
 ['26-35', 1000083],
 ['26-35', 1000083],
 ['26-35', 1000083],
 ['26-35', 1000083],
 ['18-25', 1000084],
 ['18-25', 1000084],
 ['18-25', 1000084],
 ['18-25', 1000084],
 ['18-25', 1000085],
 ['0-17', 1000086],
 ['0-17', 1000086],
 ['26-35', 1000087],
 ['26-35', 1000087],
 ['26-35', 1000087],
 ['46-50', 1000088],
 ['46-50', 1000088],
 ['46-50', 1000088],
 ['55+', 1000089],
 ['55+', 1000089],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['55+', 1000090],
 ['36-45', 1000091],
 ['36-45', 1000091],
 ['36-45', 1000091],
 ['36-45', 1000091],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['18-25', 1000092],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000093],
 ['26-35', 1000094],
 ['46-50', 1000095],
 ['46-50', 1000095],
 ['26-35', 1000096],
 ['26-35', 1000096],
 ['36-45', 1000097],
 ['36-45', 1000097],
 ['36-45', 1000097],
 ['36-45', 1000097],
 ['36-45', 1000097],
 ['36-45', 1000097],
 ['36-45', 1000097],
 ['36-45', 1000097],
 ['0-17', 1000099],
 ['0-17', 1000099],
 ['0-17', 1000099],
 ['0-17', 1000099],
 ['0-17', 1000099],
 ['36-45', 1000100],
 ['36-45', 1000100],
 ['36-45', 1000100],
 ['18-25', 1000101],
 ['18-25', 1000101],
 ['18-25', 1000101],
 ['18-25', 1000101],
 ['36-45', 1000102],
 ['36-45', 1000102],
 ['36-45', 1000102],
 ['36-45', 1000102],
 ['36-45', 1000102],
 ['36-45', 1000102],
 ['36-45', 1000102],
 ['46-50', 1000103],
 ['46-50', 1000103],
 ['46-50', 1000103],
 ['46-50', 1000103],
 ['46-50', 1000105],
 ['46-50', 1000105],
 ['46-50', 1000105],
 ['46-50', 1000105],
 ['36-45', 1000106],
 ['36-45', 1000106],
 ['36-45', 1000106],
 ['46-50', 1000107],
 ['46-50', 1000107],
 ['46-50', 1000107],
 ['46-50', 1000107],
 ['46-50', 1000107],
 ['46-50', 1000107],
 ['26-35', 1000108],
 ['46-50', 1000109],
 ['46-50', 1000109],
 ['46-50', 1000109],
 ['26-35', 1000110],
 ['36-45', 1000111],
 ['36-45', 1000111],
 ['26-35', 1000112],
 ['18-25', 1000113],
 ['18-25', 1000113],
 ['26-35', 1000114],
 ['26-35', 1000114],
 ['26-35', 1000116],
 ['26-35', 1000116],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['26-35', 1000117],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['36-45', 1000118],
 ['0-17', 1000119],
 ['0-17', 1000119],
 ['0-17', 1000119],
 ['0-17', 1000119],
 ['0-17', 1000119],
 ['26-35', 1000120],
 ['36-45', 1000121],
 ['36-45', 1000121],
 ['18-25', 1000122],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['36-45', 1000123],
 ['55+', 1000124],
 ['46-50', 1000125],
 ['46-50', 1000125],
 ['46-50', 1000125],
 ['46-50', 1000125],
 ['46-50', 1000125],
 ['46-50', 1000125],
 ['18-25', 1000126],
 ['18-25', 1000126],
 ['46-50', 1000127],
 ['46-50', 1000127],
 ['46-50', 1000127],
 ['46-50', 1000127],
 ['46-50', 1000127],
 ['55+', 1000128],
 ['26-35', 1000129],
 ['26-35', 1000129],
 ['26-35', 1000129],
 ['26-35', 1000129],
 ['26-35', 1000129],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['36-45', 1000130],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['18-25', 1000131],
 ['26-35', 1000132],
 ['26-35', 1000132],
 ['26-35', 1000132],
 ['26-35', 1000132],
 ['26-35', 1000132],
 ['26-35', 1000133],
 ['26-35', 1000133],
 ['26-35', 1000133],
 ['26-35', 1000133],
 ['26-35', 1000133],
 ['26-35', 1000134],
 ['26-35', 1000134],
 ['26-35', 1000134],
 ['26-35', 1000134],
 ['18-25', 1000135],
 ['18-25', 1000135],
 ['18-25', 1000135],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['18-25', 1000136],
 ['46-50', 1000137],
 ['46-50', 1000137],
 ['46-50', 1000137],
 ['46-50', 1000137],
 ['46-50', 1000137],
 ['46-50', 1000137],
 ['46-50', 1000137],
 ['46-50', 1000137],
 ['46-50', 1000137],
 ['18-25', 1000138],
 ['18-25', 1000138],
 ['18-25', 1000138],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['26-35', 1000139],
 ['36-45', 1000140],
 ['36-45', 1000140],
 ['26-35', 1000142],
 ['26-35', 1000142],
 ['26-35', 1000142],
 ['26-35', 1000142],
 ['26-35', 1000142],
 ['18-25', 1000143],
 ['18-25', 1000143],
 ['18-25', 1000143],
 ['18-25', 1000145],
 ['18-25', 1000145],
 ['18-25', 1000145],
 ['18-25', 1000145],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['36-45', 1000146],
 ['18-25', 1000147],
 ['18-25', 1000147],
 ['18-25', 1000147],
 ['18-25', 1000147],
 ['18-25', 1000147],
 ['18-25', 1000147],
 ['18-25', 1000147],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['51-55', 1000148],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['26-35', 1000149],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['36-45', 1000150],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['26-35', 1000151],
 ['18-25', 1000152],
 ['0-17', 1000153],
 ['0-17', 1000153],
 ['0-17', 1000153],
 ['51-55', 1000154],
 ['51-55', 1000154],
 ['51-55', 1000154],
 ['51-55', 1000154],
 ['36-45', 1000155],
 ['36-45', 1000155],
 ['36-45', 1000155],
 ['36-45', 1000155],
 ['36-45', 1000155],
 ['36-45', 1000155],
 ['36-45', 1000155],
 ['46-50', 1000156],
 ['46-50', 1000156],
 ['46-50', 1000156],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['36-45', 1000157],
 ['55+', 1000158],
 ['55+', 1000158],
 ['46-50', 1000159],
 ['36-45', 1000160],
 ['36-45', 1000160],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['46-50', 1000161],
 ['18-25', 1000162],
 ['18-25', 1000162],
 ['18-25', 1000162],
 ['18-25', 1000162],
 ['18-25', 1000162],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000163],
 ['18-25', 1000165],
 ['18-25', 1000165],
 ['18-25', 1000165],
 ['18-25', 1000165],
 ['18-25', 1000165],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],
 ['18-25', 1000166],

In [ ]:
df [['Age','User_ID']].value_counts()  # count of how many user_id or age

Age    User_ID
26-35  1001680    1026
36-45  1004277     979
       1001941     898
       1001181     862
46-50  1000889     823
                  ...
26-35  1005391       7
18-25  1005608       7
26-35  1000094       7
51-55  1005810       7
26-35  1000708       6
Name: count, Length: 5891, dtype: int64

In [ ]:
import numpy as np

In [ ]:
df['Purchase'].aggregate(np.sum)

/tmp/ipython-input-3064486952.py:1: FutureWarning: The provided callable <function sum at 0x7bc2cf76b7e0> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df['Purchase'].aggregate(np.sum)

np.int64(5095812742)

In [ ]:
df['Purchase'].aggregate([np.sum,np.mean])

/tmp/ipython-input-3826028227.py:1: FutureWarning: The provided callable <function sum at 0x7bc2cf76b7e0> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df['Purchase'].aggregate([np.sum,np.mean])
/tmp/ipython-input-3826028227.py:1: FutureWarning: The provided callable <function mean at 0x7bc2cf78c900> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df['Purchase'].aggregate([np.sum,np.mean])

sum     5.095813e+09
mean    9.263969e+03
Name: Purchase, dtype: float64

In [ ]:
df[['Product_Category_1','Product_Category_2','Product_Category_3']].aggregate([np.sum,np.mean])

/tmp/ipython-input-2191486193.py:1: FutureWarning: The provided callable <function sum at 0x7bc2cf76b7e0> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df[['Product_Category_1','Product_Category_2','Product_Category_3']].aggregate([np.sum,np.mean])
/tmp/ipython-input-2191486193.py:1: FutureWarning: The provided callable <function mean at 0x7bc2cf78c900> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df[['Product_Category_1','Product_Category_2','Product_Category_3']].aggregate([np.sum,np.mean])

      Product_Category_1  Product_Category_2  Product_Category_3
sum         2.972716e+06        5.425425e+06        6.958758e+06
mean        5.404270e+00        9.863190e+00        1.265072e+01

In [ ]:
df.Product_Category_1.apply(lambda x: x*10)

0          30
1          10
2         120
3         120
4          80
         ...
550063    200
550064    200
550065    200
550066    200
550067    200
Name: Product_Category_1, Length: 550068, dtype: int64

In [ ]:
df['Category']=df.Purchase.apply(lambda x : 'High Focused' if x > 5000 else 'General')
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Category
0,1000001,P00069042,Female,0-17,10,A,2,0,3,6.0,14.0,8370,High Focused
1,1000001,P00248942,Female,0-17,10,A,2,0,1,6.0,14.0,15200,High Focused
2,1000001,P00087842,Female,0-17,10,A,2,0,12,6.0,14.0,1422,General
3,1000001,P00085442,Female,0-17,10,A,2,0,12,14.0,14.0,1057,General
4,1000002,P00285442,Male,55+,16,C,4+,0,8,14.0,14.0,7969,High Focused

In [ ]:
df.Category.value_counts()   #count of high focused row

Category
High Focused    455145
General          94923
Name: count, dtype: int64

In [ ]:
df.groupby('Gender').groups   #group by the age of female

{'Female': [0, 1, 2, 3, 14, 15, 16, 17, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 65, 66, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 124, 125, 126, 147, 148, 149, 150, 151, 156, 157, 158, 163, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 219, 222, 223, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 297, 298, 299, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 373, ...], 'Male': [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 67, 68, 69, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 152, 153, ...]}

In [ ]:
df.groupby('Gender')['Purchase'].agg(np.sum)

/tmp/ipython-input-1164100662.py:1: FutureWarning: The provided callable <function sum at 0x7bc2cf76b7e0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('Gender')['Purchase'].agg(np.sum)

Gender
Female    1186232642
Male      3909580100
Name: Purchase, dtype: int64

In [ ]:
df.groupby('Gender')['Purchase'].apply (lambda x : x > 10000)

Gender
Female  0         False
        1          True
        2         False
        3         False
        14        False
                  ...
Male    550057    False
        550058    False
        550060    False
        550062    False
        550063    False
Name: Purchase, Length: 550068, dtype: bool

In [ ]:
df.City_Category.value_counts()  #coverting the city_category in numercial value colm

City_Category
B    231173
C    171175
A    147720
Name: count, dtype: int64

In [ ]:
dummy_df=pd.get_dummies(df.City_Category,drop_first=True,dtype=int)

In [ ]:
dummy_df.head()

   B  C
0  0  0
1  0  0
2  0  0
3  0  0
4  0  1

In [ ]:
df=pd.concat ([df,dummy_df],axis=1) #concat the colm b,c
df

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Category,B,C,B,C
0,1000001,P00069042,Female,0-17,10,A,2,0,3,6.0,14.0,8370,High Focused,0,0,0,0
1,1000001,P00248942,Female,0-17,10,A,2,0,1,6.0,14.0,15200,High Focused,0,0,0,0
2,1000001,P00087842,Female,0-17,10,A,2,0,12,6.0,14.0,1422,General,0,0,0,0
3,1000001,P00085442,Female,0-17,10,A,2,0,12,14.0,14.0,1057,General,0,0,0,0
4,1000002,P00285442,Male,55+,16,C,4+,0,8,14.0,14.0,7969,High Focused,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,Male,51-55,13,B,1,1,20,2.0,11.0,368,General,1,0,1,0
550064,1006035,P00375436,Female,26-35,1,C,3,0,20,2.0,11.0,371,General,0,1,0,1
550065,1006036,P00375436,Female,26-35,15,B,4+,1,20,2.0,11.0,137,General,1,0,1,0
550066,1006038,P00375436,Female,55+,1,C,2,0,20,2.0,11.0,365,General,0,1,0,1
550067,1006039,P00371644,Female,46-50,0,B,4+,1,20,2.0,11.0,490,General,1,0,1,0

In [ ]:
df.drop(['City_Category'],axis=1,inplace=True)

KeyError: "['City_Category'] not found in axis"

In [ ]:
df

,User_ID,Product_ID,Gender,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Category,B,C,B,C
0,1000001,P00069042,Female,0-17,10,2,0,3,6.0,14.0,8370,High Focused,0,0,0,0
1,1000001,P00248942,Female,0-17,10,2,0,1,6.0,14.0,15200,High Focused,0,0,0,0
2,1000001,P00087842,Female,0-17,10,2,0,12,6.0,14.0,1422,General,0,0,0,0
3,1000001,P00085442,Female,0-17,10,2,0,12,14.0,14.0,1057,General,0,0,0,0
4,1000002,P00285442,Male,55+,16,4+,0,8,14.0,14.0,7969,High Focused,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,Male,51-55,13,1,1,20,2.0,11.0,368,General,1,0,1,0
550064,1006035,P00375436,Female,26-35,1,3,0,20,2.0,11.0,371,General,0,1,0,1
550065,1006036,P00375436,Female,26-35,15,4+,1,20,2.0,11.0,137,General,1,0,1,0
550066,1006038,P00375436,Female,55+,1,2,0,20,2.0,11.0,365,General,0,1,0,1
550067,1006039,P00371644,Female,46-50,0,4+,1,20,2.0,11.0,490,General,1,0,1,0

In [ ]:
df.shape

(550068, 16)